name: Update static site on wiki edit

on: [gollum, push]

jobs:
  update-submodule:
    name: Update submodule
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodule
        run: |
          git submodule foreach git fetch --all
          git submodule foreach git reset --hard origin/master

      - name: Retrieve update description
        id: get-commit-message
        run: echo "description=$(git submodule -q foreach git log -n1 --format=format:%s)" >> "$GITHUB_OUTPUT"

      - name: Commit updated submodule
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.get-commit-message.outputs.description }}
          file_pattern: wiki .gitmodules

  build-static-pages:
    name: Build static pages
    needs: update-submodule
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build site
        run: bundle exec rake

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
